version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fittrack_postgres
    restart: always
    environment:
      POSTGRES_USER: fittrack_user
      POSTGRES_PASSWORD: fittrack_password
      POSTGRES_DB: fittrack_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fittrack_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
