// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlyRSRKy9FtBNuK6ZnefR5Z4MIIKmLkw',
    appId: '1:156107535041:web:d3f8a9b944f83d29adda40',
    messagingSenderId: '156107535041',
    projectId: 'fittrackpro-fitness',
    authDomain: 'fittrackpro-fitness.firebaseapp.com',
    storageBucket: 'fittrackpro-fitness.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx-qK4FWHsY3BVVP2IXeEer_tB-Xj2Q1Y',
    appId: '1:156107535041:android:81083482cd5a3418adda40',
    messagingSenderId: '156107535041',
    projectId: 'fittrackpro-fitness',
    storageBucket: 'fittrackpro-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGgv7F2Ay4l2RRrefQRwsitrn31OIu34',
    appId: '1:156107535041:ios:ab73dc067627b4e1adda40',
    messagingSenderId: '156107535041',
    projectId: 'fittrackpro-fitness',
    storageBucket: 'fittrackpro-fitness.firebasestorage.app',
    iosBundleId: 'com.fittrackpro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGGgv7F2Ay4l2RRrefQRwsitrn31OIu34',
    appId: '1:156107535041:ios:7b6414d137c240ebadda40',
    messagingSenderId: '156107535041',
    projectId: 'fittrackpro-fitness',
    storageBucket: 'fittrackpro-fitness.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlyRSRKy9FtBNuK6ZnefR5Z4MIIKmLkw',
    appId: '1:156107535041:web:6cbb2557ed516c5cadda40',
    messagingSenderId: '156107535041',
    projectId: 'fittrackpro-fitness',
    authDomain: 'fittrackpro-fitness.firebaseapp.com',
    storageBucket: 'fittrackpro-fitness.firebasestorage.app',
  );
}
